### ISSUE TITLE
Intermittent error on close method

### ISSUE THREAD

**Issue by pghalliday** [soldair/node-tailfd#2]
I am occasionally (1 in 10 times?) running into the following error when I call the close method

```
TypeError: Cannot read property 'watcher' of undefined
    at /vagrant/node_modules/tailfd/node_modules/watchfd/watch.js:288:48
    at Object.oncomplete (fs.js:107:15)
```

I'm wondering if there is some kind of race condition, possibly caused by closing the watcher from inside the line event handler.

This is the code, basically I'm watching a file for a particular line and then I stop watching (I don't think the rest is likely to be relevant but including it just in case):

``` javascript
      var timeout, child, watcher, out, err;
      var cleanUp = function() {
        watcher.close();
        fs.closeSync(out);
        fs.closeSync(err);
        clearTimeout(timeout);        
        child.removeListener('exit', exitHandler);
      };
      var exitHandler = function() {
        cleanUp();
        grunt.fail.warn(new Error('Exited.'));
      };
      var timeoutHandler = function() {
        cleanUp();
        child.kill();
        grunt.fail.warn(new Error('Timed out.'));
      };
      var end = function() {
        cleanUp();
        done();
      };
      fs.createFileSync(tunnelLogFile);
      fs.createFileSync(tunnelPidFile);
      out = fs.openSync(tunnelLogFile, 'a');
      err = fs.openSync(tunnelLogFile, 'a');
      watcher = tail(tunnelLogFile,function(line,tailInfo){
        grunt.log.writeln(line);
        if (line === 'Press Ctrl-C to exit') {
          end();
        }
      });
      child = spawn('java', options, {
        detached: true,
        stdio: ['ignore', out, err]
      });
      fs.writeFileSync(tunnelPidFile, child.pid, {
        flag: 'w+'
      });
      child.on('exit', exitHandler);
      child.unref();
      timeout = setTimeout(timeoutHandler, grunt.config('browserstackTunnel.timeout') || DEFAULT_TUNNEL_START_TIMEOUT);
```

**Comment by soldair** [comment]
interesting ill check this out. thanks!

**Comment by soldair** [comment]
could you try with tailfd 0.1.5 ? pushed to npm.

**Comment by pghalliday** [comment]
So far so good - I have run it quite a few times without error now :)
Will keep an eye on it and let you know if i run into this again.

Thanks for the quick fix!
